---
deployment:
 tasks:
 - export DEPLOYPATH=/home/cheetahb/public_html/
 - /bin/cp -R /public/.htaccess $DEPLOYPATH
 - /bin/cp -R /public/favicon.ico $DEPLOYPATH
 - /bin/cp -R /public/index.html $DEPLOYPATH
 - /bin/cp -R /public/logo192.png $DEPLOYPATH
 - /bin/cp -R /public/logo512.png $DEPLOYPATH
 - /bin/cp -R /public/manifest.json $DEPLOYPATH
 - /bin/cp -R /public/robots.txt $DEPLOYPATH